######################################################################
##
## Filename: dynamics_tb.udo
## Created on: Tue Dec 09 10:25:30 AM PST 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
