######################################################################
##
## Filename: fast_forward_beat_gen_tb.udo
## Created on: Sat Dec 06 05:26:34 PM PST 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
