######################################################################
##
## Filename: music_player_tb_nosound.udo
## Created on: Mon Dec 01 11:07:45 AM PST 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
