######################################################################
##
## Filename: music_player_tb.udo
## Created on: Sun Dec 07 07:14:05 PM PST 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
