######################################################################
##
## Filename: note_display_tb.udo
## Created on: Mon Dec 01 12:12:02 PM PST 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
