######################################################################
##
## Filename: note_player.udo
## Created on: Mon Dec 01 11:15:28 AM PST 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
