######################################################################
##
## Filename: wave_display_2_tb.udo
## Created on: Tue Dec 02 08:10:42 PM PST 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
